SELECT 
    NAME = 
    CASE 
        WHEN OCCUPATION ='ACTOR' THEN NAME+'(A)'
        WHEN OCCUPATION='SINGER' THEN NAME+'(S)'
        WHEN OCCUPATION='DOCTOR' THEN NAME+'(D)'
        ELSE NAME+'(P)'
    END
FROM OCCUPATIONS ORDER BY NAME;

SELECT 
    'There are a total of ', COUNT(OCCUPATION),LOWER(OCCUPATION)+'s.'
FROM 
    OCCUPATIONS 
GROUP BY 
    OCCUPATION 
ORDER BY 
    COUNT(OCCUPATION) ASC, OCCUPATION;